<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="GridviewResponsive.Default" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Ordre </title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="Content/bootstrap.cosmo.min.css" rel="stylesheet" />
    <link href="Content/StyleSheet.css" rel="stylesheet" />
 </head>
<body>
    <form id="form1" runat="server">
        <br />
        
            
         <div id="mainContainer" class="container" >
                               <div class="table-responsive"  > 
           
                                   <asp:GridView ID="GridView1" runat="server" Width="100%" 
                                       CssClass="table-responsive" 
                                        AutoGenerateColumns="False"
                                           DataKeyNames="Varenr" EmptyDataText="There are no data records to display." AllowSorting="True"
                                           AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"
                                          EnablePersistedSelection="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" 
                                          OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" 
                                          ShowFooter="True" OnRowDeleting="GridView1_RowDeleting" OnSorting="GridView1_Sorting" OnRowDataBound="GridView1_RowDataBound" >
                                        <Columns>
                                            <asp:TemplateField HeaderText="Varenr" SortExpression="Varenr">
                                                <EditItemTemplate>
                                                    <asp:Label ID="Label1" runat="server" Text='<%# Eval("Varenr") %>'></asp:Label>
                                                </EditItemTemplate>
                                                <FooterTemplate>
                                                    <asp:LinkButton ID="Nybtn" runat="server" OnClick="Nybtn_Click">Legge til</asp:LinkButton>
                                                </FooterTemplate>
                                                <ItemTemplate>
                                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("Varenr") %>'></asp:Label>
                                                </ItemTemplate>
                                             </asp:TemplateField>
                                            <asp:TemplateField HeaderText="Varenavn" SortExpression="Varenavn">
                                                <EditItemTemplate>
                                                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Varenavn") %>'></asp:TextBox>
                                                </EditItemTemplate>
                                                <FooterTemplate>
                                                    <asp:TextBox ID="TextBox7" runat="server"></asp:TextBox>
                                                </FooterTemplate>
                                                <ItemTemplate>
                                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("Varenavn") %>'></asp:Label>
                                                </ItemTemplate>
                                             </asp:TemplateField>
                                            <asp:TemplateField HeaderText="Ansvarlig" SortExpression="Ansvarlig" >
                                                <EditItemTemplate>
                                                    <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Ansvarlig") %>'></asp:TextBox>
                                                </EditItemTemplate>
                                                <FooterTemplate>
                                                    <asp:TextBox ID="TextBox8" runat="server"></asp:TextBox>
                                                </FooterTemplate>
                                                <ItemTemplate>
                                                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("Ansvarlig") %>'></asp:Label>
                                                </ItemTemplate>
                                             </asp:TemplateField>
                                            <asp:TemplateField HeaderText="Kunde" SortExpression="Kunde">
                                                <EditItemTemplate>
                                                    <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Kunde") %>'></asp:TextBox>
                                                </EditItemTemplate>
                                                <FooterTemplate>
                                                    <asp:TextBox ID="TextBox9" runat="server"></asp:TextBox>
                                                </FooterTemplate>
                                                <ItemTemplate>
                                                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("Kunde") %>'></asp:Label>
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                            <asp:TemplateField HeaderText="Bestillinsdato" SortExpression="Bestillinsdato">
                                                    <ItemTemplate>
                                                    <asp:Label ID="Label5" runat="server" Text='<%# Bind("Bestillinsdato") %>'></asp:Label>
                                                </ItemTemplate>
                                             <EditItemTemplate>
                                                    <asp:TextBox ID="TextBox14" runat="server" Text='<%# Bind("Bestillinsdato") %>'></asp:TextBox>
                                                    <ajaxToolkit:CalendarExtender ID="TextBox14_CalendarExtender" runat="server" BehaviorID="ctl15_TextBox14_CalendarExtender"  SelectedDate='<%# Bind("Bestillinsdato") %>' TargetControlID="TextBox14" ClearTime="True" DaysModeTitleFormat="dd.MM.yyyy" Format="dd.MM.yyyy"  TodaysDateFormat="dd.MM.yyyy" />
                                                </EditItemTemplate>
                                                <FooterTemplate>
                                                    <asp:TextBox ID="TextBox10" runat="server"></asp:TextBox>
                                                    <ajaxToolkit:CalendarExtender ID="TextBox10_CalendarExtender" runat="server" Format="dd.MM.yyyy" TargetControlID="TextBox10" />
                                                </FooterTemplate>
                                            </asp:TemplateField>
                                            <asp:TemplateField HeaderText="ForventetLevering" SortExpression="ForventetLevering">
                                                <EditItemTemplate>
                                                    <asp:TextBox ID="TextBox13" runat="server" Text='<%# Bind("ForventetLevering") %>'></asp:TextBox>
                                                    <ajaxToolkit:CalendarExtender ID="TextBox13_CalendarExtender" runat="server" TargetControlID="TextBox13" BehaviorID="ctl20_TextBox13_CalendarExtender" ClearTime="True" DaysModeTitleFormat="dd.MM.yyyy" Format="dd.MM.yyyy" SelectedDate='<%# Bind("ForventetLevering") %>' TodaysDateFormat="dd.MM.yyyy" />
                                                </EditItemTemplate>
                                                <FooterTemplate>
                                                    <asp:TextBox ID="TextBox11" runat="server"></asp:TextBox>
                                                    <ajaxToolkit:CalendarExtender ID="TextBox11_CalendarExtender" runat="server" Format="dd.MM.yyyy" TargetControlID="TextBox11" />
                                                </FooterTemplate>
                                                <ItemTemplate>
                                                    <asp:Label ID="Label6" runat="server" Text='<%# Bind("ForventetLevering") %>'></asp:Label>
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                            <asp:TemplateField HeaderText="Levertdato" SortExpression="Levertdato">
                                                <EditItemTemplate>
                                                    <asp:TextBox ID="TextBox6" runat="server" Text='<%# Bind("Levertdato") %>'></asp:TextBox>
                                                    <ajaxToolkit:CalendarExtender ID="TextBox6_CalendarExtender" runat="server" BehaviorID="ctl17_TextBox6_CalendarExtender" Format="dd.MM.yyyy" SelectedDate='<%# Bind("Levertdato") %>' TargetControlID="TextBox6" />
                                                </EditItemTemplate>
                                                <FooterTemplate>
                                                    <asp:TextBox ID="TextBox12" runat="server"></asp:TextBox>
                                                    <ajaxToolkit:CalendarExtender ID="TextBox12_CalendarExtender" runat="server" Format="dd.MM.yyyy" TargetControlID="TextBox12" />
                                                </FooterTemplate>
                                                <ItemTemplate>
                                                    <asp:Label ID="Label7" runat="server" Text='<%# Bind("Levertdato") %>'></asp:Label>
                                                </ItemTemplate>
                                             </asp:TemplateField>
                                         </Columns>
                                          <EmptyDataTemplate>
                                              No rows found
                                          </EmptyDataTemplate>
                                    </asp:GridView>
                                </div>
               </div>
    
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
    
    </form>
</body>
</html>
