#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridviewResponsive
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_9CAD65_tamilsangam")]
	public partial class NorthwindDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsmi_order(smi_order instance);
    partial void Updatesmi_order(smi_order instance);
    partial void Deletesmi_order(smi_order instance);
    #endregion
		
		public NorthwindDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NorthwindConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NorthwindDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NorthwindDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NorthwindDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NorthwindDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<smi_order> smi_orders
		{
			get
			{
				return this.GetTable<smi_order>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.smi_order")]
	public partial class smi_order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Varenr;
		
		private string _Ansvarlig;
		
		private string _Kunde;
		
		private string _Varenavn;
		
		private System.Nullable<System.DateTime> _Bestillinsdato;
		
		private System.Nullable<System.DateTime> _ForventetLevering;
		
		private System.Nullable<System.DateTime> _Levertdato;
		
		private System.Nullable<bool> _haster;
		
		private int _ordernr;
		
		private System.Nullable<bool> _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVarenrChanging(int value);
    partial void OnVarenrChanged();
    partial void OnAnsvarligChanging(string value);
    partial void OnAnsvarligChanged();
    partial void OnKundeChanging(string value);
    partial void OnKundeChanged();
    partial void OnVarenavnChanging(string value);
    partial void OnVarenavnChanged();
    partial void OnBestillinsdatoChanging(System.Nullable<System.DateTime> value);
    partial void OnBestillinsdatoChanged();
    partial void OnForventetLeveringChanging(System.Nullable<System.DateTime> value);
    partial void OnForventetLeveringChanged();
    partial void OnLevertdatoChanging(System.Nullable<System.DateTime> value);
    partial void OnLevertdatoChanged();
    partial void OnhasterChanging(System.Nullable<bool> value);
    partial void OnhasterChanged();
    partial void OnordernrChanging(int value);
    partial void OnordernrChanged();
    partial void OndeletedChanging(System.Nullable<bool> value);
    partial void OndeletedChanged();
    #endregion
		
		public smi_order()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Varenr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Varenr
		{
			get
			{
				return this._Varenr;
			}
			set
			{
				if ((this._Varenr != value))
				{
					this.OnVarenrChanging(value);
					this.SendPropertyChanging();
					this._Varenr = value;
					this.SendPropertyChanged("Varenr");
					this.OnVarenrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ansvarlig", DbType="VarChar(500)")]
		public string Ansvarlig
		{
			get
			{
				return this._Ansvarlig;
			}
			set
			{
				if ((this._Ansvarlig != value))
				{
					this.OnAnsvarligChanging(value);
					this.SendPropertyChanging();
					this._Ansvarlig = value;
					this.SendPropertyChanged("Ansvarlig");
					this.OnAnsvarligChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kunde", DbType="VarChar(850)")]
		public string Kunde
		{
			get
			{
				return this._Kunde;
			}
			set
			{
				if ((this._Kunde != value))
				{
					this.OnKundeChanging(value);
					this.SendPropertyChanging();
					this._Kunde = value;
					this.SendPropertyChanged("Kunde");
					this.OnKundeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Varenavn", DbType="VarChar(100)")]
		public string Varenavn
		{
			get
			{
				return this._Varenavn;
			}
			set
			{
				if ((this._Varenavn != value))
				{
					this.OnVarenavnChanging(value);
					this.SendPropertyChanging();
					this._Varenavn = value;
					this.SendPropertyChanged("Varenavn");
					this.OnVarenavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bestillinsdato", DbType="DateTime")]
		public System.Nullable<System.DateTime> Bestillinsdato
		{
			get
			{
				return this._Bestillinsdato;
			}
			set
			{
				if ((this._Bestillinsdato != value))
				{
					this.OnBestillinsdatoChanging(value);
					this.SendPropertyChanging();
					this._Bestillinsdato = value;
					this.SendPropertyChanged("Bestillinsdato");
					this.OnBestillinsdatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForventetLevering", DbType="DateTime")]
		public System.Nullable<System.DateTime> ForventetLevering
		{
			get
			{
				return this._ForventetLevering;
			}
			set
			{
				if ((this._ForventetLevering != value))
				{
					this.OnForventetLeveringChanging(value);
					this.SendPropertyChanging();
					this._ForventetLevering = value;
					this.SendPropertyChanged("ForventetLevering");
					this.OnForventetLeveringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Levertdato", DbType="DateTime")]
		public System.Nullable<System.DateTime> Levertdato
		{
			get
			{
				return this._Levertdato;
			}
			set
			{
				if ((this._Levertdato != value))
				{
					this.OnLevertdatoChanging(value);
					this.SendPropertyChanging();
					this._Levertdato = value;
					this.SendPropertyChanged("Levertdato");
					this.OnLevertdatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haster", DbType="Bit")]
		public System.Nullable<bool> haster
		{
			get
			{
				return this._haster;
			}
			set
			{
				if ((this._haster != value))
				{
					this.OnhasterChanging(value);
					this.SendPropertyChanging();
					this._haster = value;
					this.SendPropertyChanged("haster");
					this.OnhasterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordernr", DbType="Int NOT NULL")]
		public int ordernr
		{
			get
			{
				return this._ordernr;
			}
			set
			{
				if ((this._ordernr != value))
				{
					this.OnordernrChanging(value);
					this.SendPropertyChanging();
					this._ordernr = value;
					this.SendPropertyChanged("ordernr");
					this.OnordernrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit")]
		public System.Nullable<bool> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
